CREATE TABLE IF NOT EXISTS bot_config
(
  id   INTEGER PRIMARY KEY CHECK (id = 1),
  data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS facts
(
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  content     TEXT NOT NULL,
  tags        TEXT NOT NULL DEFAULT '[]',
  usernames   TEXT NOT NULL DEFAULT '[]',
  created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);
